export async function GET() {
  const imageInfo: FoodItem[] = [
    {
      id: 1,
      name: "Cheeseburger",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/50/4608/3072",
      categories: ["Fast Food", "Burgers"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Ketchup", selected: false },
        { name: "Mustard", selected: false },
        { name: "Lettuce", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 2,
      name: "Spaghetti Bolognese",
      prepareTime: "25 minutes",
      image: "https://picsum.photos/id/51/5000/3333",
      categories: ["Italian", "Pasta"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Parmesan Cheese", selected: false },
        { name: "Garlic Bread", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 3,
      name: "Pepperoni Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/52/1280/853",
      categories: ["Fast Food", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Extra Cheese", selected: false },
        { name: "Peppers", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 4,
      name: "Sushi Platter",
      prepareTime: "45 minutes",
      image: "https://picsum.photos/id/53/1280/1280",
      categories: ["Japanese", "Sushi"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Soy Sauce", selected: false },
        { name: "Wasabi", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 5,
      name: "Garden Salad",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/54/3264/2176",
      categories: ["Healthy", "Salads"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Croutons", selected: false },
        { name: "Dressing", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 6,
      name: "Chicken Tenders",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/55/4608/3072",
      categories: ["Fast Food", "Chicken"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Ketchup", selected: false },
        { name: "Honey Mustard", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 7,
      name: "Lasagna",
      prepareTime: "35 minutes",
      image: "https://picsum.photos/id/56/2880/1920",
      categories: ["Italian", "Pasta"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Garlic Bread", selected: false },
        { name: "Salad", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 8,
      name: "Steak",
      prepareTime: "25 minutes",
      image: "https://picsum.photos/id/57/2448/3264",
      categories: ["Grilled", "Meat"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Mushrooms", selected: false },
        { name: "Gravy", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 9,
      name: "Fish Tacos",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/58/1280/853",
      categories: ["Seafood", "Tacos"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Salsa", selected: false },
        { name: "Guacamole", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 10,
      name: "Fruit Smoothie",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/59/2464/1632",
      categories: ["Healthy", "Smoothies"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Protein Powder", selected: false },
        { name: "Honey", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 11,
      name: "Sashimi",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/60/1920/1200",
      categories: ["Japanese", "Sushi"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Soy Sauce", selected: false },
        { name: "Wasabi", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 12,
      name: "Caprese Salad",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/61/3264/2448",
      categories: ["Italian", "Salads"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Balsamic Glaze", selected: false },
        { name: "Croutons", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 13,
      name: "Bruschetta",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/62/2000/1333",
      categories: ["Italian", "Appetizers"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Balsamic Glaze", selected: false },
        { name: "Fresh Basil", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 14,
      name: "Chocolate Brownie",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/63/5000/2813",
      categories: ["Desserts", "Brownies"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Vanilla Ice Cream", selected: false },
        { name: "Hot Fudge", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 15,
      name: "Margarita Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/64/4326/2884",
      categories: ["Italian", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Extra Cheese", selected: false },
        { name: "Basil Leaves", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 16,
      name: "Chicken Alfredo",
      prepareTime: "25 minutes",
      image: "https://picsum.photos/id/65/4912/3264",
      categories: ["Italian", "Pasta"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Garlic Bread", selected: false },
        { name: "Salad", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 17,
      name: "Nachos",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/66/3264/2448",
      categories: ["Mexican", "Appetizers"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Salsa", selected: false },
        { name: "Guacamole", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 18,
      name: "Caesar Salad",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/67/2848/4288",
      categories: ["Salads", "Healthy"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Chicken", selected: false },
        { name: "Croutons", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 19,
      name: "Double Cheese Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/68/4608/3072",
      categories: ["Fast Food", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Extra Cheese", selected: false },
        { name: "Peppers", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 20,
      name: "Chicken Burrito",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/69/4912/3264",
      categories: ["Mexican", "Burritos"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Sour Cream", selected: false },
        { name: "Guacamole", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 21,
      name: "Chicken Tikka Masala",
      prepareTime: "40 minutes",
      image: "https://picsum.photos/id/70/3011/2000",
      categories: ["Indian", "Chicken"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Naan Bread", selected: false },
        { name: "Rice", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 22,
      name: "Shrimp Scampi",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/71/5000/3333",
      categories: ["Seafood", "Italian"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Garlic Bread", selected: false },
        { name: "Salad", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 23,
      name: "Grilled Cheese Sandwich",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/72/3000/2000",
      categories: ["Sandwiches", "Comfort Food"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Tomato Soup", selected: false },
        { name: "Bacon", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 24,
      name: "Miso Soup",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/73/5000/3333",
      categories: ["Japanese", "Soup"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Tofu", selected: false },
        { name: "Green Onions", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 25,
      name: "Pancakes",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/74/4288/2848",
      categories: ["Breakfast", "American"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Maple Syrup", selected: false },
        { name: "Whipped Cream", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 26,
      name: "Pho",
      prepareTime: "35 minutes",
      image: "https://picsum.photos/id/75/5616/3744",
      categories: ["Vietnamese", "Soup"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Bean Sprouts", selected: false },
        { name: "Lime Wedges", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 27,
      name: "BBQ Ribs",
      prepareTime: "45 minutes",
      image: "https://picsum.photos/id/76/7360/4912",
      categories: ["American", "BBQ"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Cornbread", selected: false },
        { name: "Cole Slaw", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 28,
      name: "Cobb Salad",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/77/5472/3648",
      categories: ["Salads", "American"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Chicken", selected: false },
        { name: "Bacon Bits", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 29,
      name: "Tiramisu",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/78/5184/3456",
      categories: ["Desserts", "Italian"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Whipped Cream", selected: false },
        { name: "Chocolate Shavings", selected: false },
        // Add more add-ons here as needed
      ],
    },
    {
      id: 30,
      name: "Fish and Chips",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/79/5472/3648",
      categories: ["Seafood", "British"],
      customerFavorite: Math.random() < 0.5,
      featured: Math.random() < 0.7,
      rating: +(Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
      price: +(Math.random() * 20).toFixed(2),
      addOns: [
        { name: "Malt Vinegar", selected: false },
        { name: "Tartar Sauce", selected: false },
        // Add more add-ons here as needed
      ],
    },
  ];

  const jsonified = JSON.stringify(imageInfo);
  console.log("Making request");
  return new Response(jsonified, {
    status: 200,
  });
}
