export async function GET() {
  const imageInfo: FoodItem[] = [
    {
      id: 1,
      name: "Cheeseburger",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/50/4608/3072",
      categories: ["Fast Food", "Burgers"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1), // Random rating between 1 to 5 (with one decimal place)
      ratingCount: Math.floor(Math.random() * 100), // Random count of people who have given a rating
    },
    {
      id: 2,
      name: "Spaghetti Bolognese",
      prepareTime: "25 minutes",
      image: "https://picsum.photos/id/51/5000/3333",
      categories: ["Italian", "Pasta"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 3,
      name: "Pepperoni Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/52/1280/853",
      categories: ["Fast Food", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 4,
      name: "Sushi Platter",
      prepareTime: "45 minutes",
      image: "https://picsum.photos/id/53/1280/1280",
      categories: ["Japanese", "Sushi"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 5,
      name: "Garden Salad",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/54/3264/2176",
      categories: ["Healthy", "Salads"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 6,
      name: "Chicken Tenders",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/55/4608/3072",
      categories: ["Fast Food", "Chicken"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 7,
      name: "Lasagna",
      prepareTime: "35 minutes",
      image: "https://picsum.photos/id/56/2880/1920",
      categories: ["Italian", "Pasta"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 8,
      name: "Steak",
      prepareTime: "25 minutes",
      image: "https://picsum.photos/id/57/2448/3264",
      categories: ["Grilled", "Meat"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 9,
      name: "Fish Tacos",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/58/1280/853",
      categories: ["Seafood", "Tacos"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 10,
      name: "Fruit Smoothie",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/59/2464/1632",
      categories: ["Healthy", "Smoothies"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 11,
      name: "Sashimi",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/60/1920/1200",
      categories: ["Japanese", "Sushi"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 12,
      name: "Caprese Salad",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/61/3264/2448",
      categories: ["Italian", "Salads"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 13,
      name: "Bruschetta",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/62/2000/1333",
      categories: ["Italian", "Appetizers"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 14,
      name: "Chocolate Brownie",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/63/5000/2813",
      categories: ["Desserts", "Brownies"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 15,
      name: "Margarita Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/64/4326/2884",
      categories: ["Italian", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 15,
      name: "Margarita Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/64/4326/2884",
      categories: ["Italian", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 16,
      name: "Chicken Alfredo",
      prepareTime: "25 minutes",
      image: "https://picsum.photos/id/65/4912/3264",
      categories: ["Italian", "Pasta"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 17,
      name: "Nachos",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/66/3264/2448",
      categories: ["Mexican", "Appetizers"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 18,
      name: "Caesar Salad",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/67/2848/4288",
      categories: ["Salads", "Healthy"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 19,
      name: "Double Cheese Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/68/4608/3072",
      categories: ["Fast Food", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 20,
      name: "Chicken Burrito",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/69/4912/3264",
      categories: ["Mexican", "Burritos"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 21,
      name: "Chicken Tikka Masala",
      prepareTime: "40 minutes",
      image: "https://picsum.photos/id/70/3011/2000",
      categories: ["Indian", "Chicken"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 22,
      name: "Shrimp Scampi",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/71/5000/3333",
      categories: ["Seafood", "Italian"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 23,
      name: "Grilled Cheese Sandwich",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/72/3000/2000",
      categories: ["Sandwiches", "Comfort Food"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 24,
      name: "Miso Soup",
      prepareTime: "10 minutes",
      image: "https://picsum.photos/id/73/5000/3333",
      categories: ["Japanese", "Soup"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 25,
      name: "Pancakes",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/74/4288/2848",
      categories: ["Breakfast", "American"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 26,
      name: "Fried Rice",
      prepareTime: "25 minutes",
      image: "https://picsum.photos/id/75/1999/2998",
      categories: ["Chinese", "Rice"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 27,
      name: "Sushi Roll",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/76/4912/3264",
      categories: ["Japanese", "Sushi"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 28,
      name: "Hamburger",
      prepareTime: "20 minutes",
      image: "https://picsum.photos/id/77/1631/1102",
      categories: ["Fast Food", "Burgers"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 29,
      name: "Veggie Pizza",
      prepareTime: "30 minutes",
      image: "https://picsum.photos/id/78/1584/2376",
      categories: ["Vegetarian", "Pizza"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
    {
      id: 30,
      name: "Tiramisu",
      prepareTime: "15 minutes",
      image: "https://picsum.photos/id/79/2000/3011",
      categories: ["Desserts", "Italian"],
      customerFavorite: Math.random() < 0.5,
      rating: (Math.random() * 5).toFixed(1),
      ratingCount: Math.floor(Math.random() * 100),
    },
  ];

  const jsonified = JSON.stringify(imageInfo);

  return new Response(jsonified, {
    status: 200,
  });
}
